const images = [
  {
    id: 1,
    image: "/assets/images/header-background-image-1.jpg",
    title: "title 1",
    caption: "image 1",
    alt: "Slide Image 1",
  },
  {
    id: 2,
    image: "/assets/images/header-background-image-2.jpg",
    title: "title 2",
    caption: "image 2",
    alt: "Slide Image 2",
  },
  {
    id: 3,
    image: "/assets/images/header-background-image-3.jpg",
    title: "title 3",
    caption: "image 3",
    alt: "Slide Image 3",
  },
  {
    id: 4,
    image: "/assets/images/header-background-image-4.jpg",
    title: "title 4",
    caption: "image 4",
    alt: "Slide Image 4",
  },
  {
    id: 5,
    image: "/assets/images/Header-background-image-5.jpg",
    title: "title 5",
    caption: "image 5",
    alt: "Slide Image 5",
  },
  {
    id: 6,
    image: "/assets/images/Header-background-image-6.jpg",
    title: "title 6",
    caption: "image 6",
    alt: "Slide Image 6",
  },
  {
    id: 7,
    image: "/assets/images/Header-background-image-7.jpg",
    title: "title 7",
    caption: "image 7",
    alt: "Slide Image 7",
  },
  {
    id: 8,
    image: "/assets/images/Header-background-image-8.jpg",
    title: "title 8",
    caption: "image 8",
    alt: "Slide Image 8",
  },
  {
    id: 9,
    image: "/assets/images/Header-background-image-9.jpg",
    title: "title 9",
    caption: "image 9",
    alt: "Slide Image 9",
  },
  {
    id: 10,
    image: "/assets/images/Header-background-image-10.jpg",
    title: "title 10",
    caption: "image 10",
    alt: "Slide Image 10",
  },
  {
    id: 11,
    image: "/assets/images/Header-background-image-11.jpg",
    title: "title 11",
    caption: "image 11",
    alt: "Slide Image 11",
  },
  {
    id: 12,
    image: "/assets/images/Header-background-image-12.jpg",
    title: "title 12",
    caption: "image 12",
    alt: "Slide Image 12",
  },
  {
    id: 13,
    image: "/assets/images/Header-background-image-13.jpg",
    title: "title 13",
    caption: "image 13",
    alt: "Slide Image 13",
  },
];

export default images;
